import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

function App(){
 const [query,setQuery]=useState(''); const [results,setResults]=useState([]); const [error,setError]=useState(''); const [loading,setLoading]=useState(false);
 async function submit(e){e.preventDefault();setError('');setResults([]);setLoading(true);try{const r=await fetch(`http://localhost:3001/api/services?query=${encodeURIComponent(query)}`);const d=await r.json();if(!r.ok)throw new Error(d.error||'Request failed');setResults(d.results)}catch(err){setError(err.message)}finally{setLoading(false)}}
 return <div className="app"><a className="skip" href="#main">Skip to main content</a><header><div className="brand">Public Service Finder</div><nav aria-label="Primary"><a href="#services">Services</a><a href="#about">About</a></nav></header><main id="main"><section className="hero" aria-labelledby="title"><p className="eyebrow">Accessibility-first foundation</p><h1 id="title">Find a government service</h1><p>Search a small representative service catalogue through an accessible client-to-server workflow.</p><form onSubmit={submit} aria-describedby="search-help"><label htmlFor="query">Service keyword</label><div className="search-row"><input id="query" value={query} onChange={e=>setQuery(e.target.value)} placeholder="e.g. passport"/><button type="submit" disabled={loading}>{loading?'Searching…':'Search services'}</button></div><p id="search-help" className="help">Try passport, health, tax, or education.</p></form></section><section id="services" aria-labelledby="results-title"><h2 id="results-title">Results</h2><div aria-live="polite" aria-atomic="true">{loading&&<p>Searching for services…</p>}{error&&<p className="error" role="alert">{error}</p>}{!loading&&!error&&results.length===0&&<p>Search to see available services.</p>}</div><ul className="results">{results.map(x=><li key={x.id}><h3>{x.name}</h3><p>{x.description}</p><span>{x.category}</span></li>)}</ul></section></main><footer id="about"><p>Demo foundation for an accessibility and architecture audit.</p></footer></div>
}
createRoot(document.getElementById('root')).render(<App/>);
